# Generated by Django 5.2.5 on 2025-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_remove_memory_image_memoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
