# Generated by Django 5.2.5 on 2025-08-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_memory_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='comment',
        ),
        migrations.AddField(
            model_name='memoryimage',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
