# Generated by Django 5.2.5 on 2025-08-19 16:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_remove_memory_comment_memoryimage_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppreciationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
