# Generated by Django 5.2.5 on 2025-08-19 18:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_appreciationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(choices=[('chapter1', 'Chapter 1'), ('chapter2', 'Chapter 2'), ('chapter3', 'Chapter 3')], max_length=20, unique=True)),
                ('audio', cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio')),
            ],
        ),
    ]
