# Generated by Django 5.2.5 on 2025-08-19 18:56

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_chaptermusic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptermusic',
            name='audio',
        ),
        migrations.AddField(
            model_name='chaptermusic',
            name='music_file',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='music'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chaptermusic',
            name='chapter',
            field=models.CharField(choices=[('chapter1', 'Chapter 1'), ('chapter2', 'Chapter 2'), ('chapter3', 'Chapter 3'), ('post-chapter3', 'Post Chapter 3')], max_length=20, unique=True),
        ),
    ]
