# Generated by Django 5.2.5 on 2025-08-19 18:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_remove_chaptermusic_audio_chaptermusic_music_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermusic',
            name='music_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio'),
        ),
    ]
