# Generated by Django 5.2.5 on 2025-08-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0008_alter_chaptermusic_music_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
